---
- hosts: localhost
  tasks:
    - name: Remove old version of docker
      yum:
        name: docker
        state: absent
        
    - name: Install docker dependencies
      yum:
        name: {{item}}
        update_cache: yes
        state: latest
      with_items:
       - curl
       - yum-utils
       - device-mapper-persistent-data
       - lvm2
    
    - name: install docker repo
      shell: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        
    - name: Install Docker-CE
      yum:
        name: docker-ce
        update_cache: yes
        state: present

    - name: Start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes
        
    - name: download and install pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /opt/
    
    - name: install pip
      shell: |
        python /opt/get-pip.py
        pip install docker-py
        
    - name: create conjur docker network
      docker_network:
        name: conjur
        
    - name: create conjur docker volume
      docker_volume:
        name: conjur
    
    - name: Load Conjur tar
      docker_image:
        load_path: /opt/conjur.tar
        state: present
    
    - name: Start conjur container
      docker_container:
         name: conjur
         image: registry2.itci.conjur.net/conjur-appliance:5.0-stable
         state: started
         privileged: yes
         networks:
          - name: conjur
         published_ports:
          - "443:443"
        volumes:
         - "conjur:/opt/conjur/etc/ssl"
         restart_policy: Always

    - name: configure conjur container
      shell: |
        docker exec conjur evoke configure master -h conjur -p Cyberark1 cyberark

    - name: Start Conjur CLI
      docker_container:
        name: conjur-cli
        image: cyberark/conjur-cli:5-6.1.0
        state: started
        volumes:
         - "conjur:/pem"
        restart_policy: Always
         
    - name: Start Jenkins  
      docker_container:
        name: jenkins
        image: captainfluffytoes/demo_conjur_docker_jenkins
        state: started
        env:
          JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
        published_ports: 
         - "8080:8080" 
        networks:
         - name: conjur
        volumes:
         - "/var/run/docker.sock:/var/run/docker.sock"
         - "./scripts:/scripts"
         - "conjur:/pem"
        restart_policy: Always
        
    - name: download weavescope
      get_url:
        url: git.io/scope
        dest: /usr/local/bin/scope
        mode: 0755
        
    - name: launch weavescope
      shell: |
        /usr/local/bin/scope launch
      ignore_errors: yes