---
- name: Build jenkins image
  docker_image:
    name: conjur_jenkins
    path: "{{ role_path }}/files/"
    state: present
    force: yes

- name: Start Jenkins
  docker_container:
    name: jenkins
    image: conjur_jenkins:latest
    state: started
    user: root
    published_ports:
     - "8080:8080"
     - "50000:50000"
    networks:
     - name: conjur
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "conjur_cert:/conjur_cert"
     - "hostfactoryTokens:/hostfactoryTokens"
     - "identity:/identity"
    restart_policy: always
    recreate: yes
