---
- name: install python jenkins
  pip:
    name: "{{ item }}"
    state: present
  with_items:
   - python-jenkins
   - lxml

- name: Build curl image
  docker_image:
    name: curl_image
    path: "{{ role_path }}/files/curlContainer/"
    state: present
    force: yes

- name: Build jenkins image
  docker_image:
    name: "{{ jenkins_image_name }}"
    path: "{{ role_path }}/files/jenkins/"
    state: present
    force: yes

- name: Start Jenkins
  docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image_name }}"
    state: started
    user: root
    published_ports:
     - "{{ jenkins_port }}:8080"
     - "50000:50000"
    networks:
     - name: conjur
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "conjur_cert:/conjur_cert"
     - "hostfactoryTokens:/hostfactoryTokens"
     - "identity:/identity"
    restart_policy: always
    recreate: yes

- name: create identity file for jenkins
  shell: |
    docker exec conjur-cli bash -c "cd /scripts/ && bash 1_hfTokenREST.sh automate && bash 2_obtainIdentityREST.sh automate"
    docker exec {{ jenkins_container_name }} cp /identity/.netrc /root/.netrc
    docker exec {{ jenkins_container_name }} cp /identity/.conjurrc /root/.conjurrc
    docker exec {{ jenkins_container_name }} cp /identity/conjur-{{ conjur_account }}.pem /root/conjur-{{ conjur_account }}.pem

- name: Wait for jenkins to start
  uri:
    url: "{{ jenkins_url }}"
    return_content: yes
  register: webpage
  until: '"New Item" in webpage.content'
  retries: 60
  delay: 3

- name: Create gitlab creds SHELL
  shell: |
    curl -s -X POST 'http://localhost:8080/credentials/store/system/domain/_/createCredentials' --data-urlencode 'json={"": "0","credentials": {"scope": "GLOBAL","id": "gitlabcred","username": "root", "password": "Cyberark1", "description": "", "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"}}'

- name: Set Up Lab1_Summon
  jenkins_job:
    name: LAB1_Summon
    config: "{{ job1_config }}"
    url: "{{ jenkins_url }}"
    state: present

- name: Set up Lab2_Containers
  jenkins_job:
    name: LAB2_Containers
    config: "{{ job2_config }}"
    url: "{{ jenkins_url }}"
    state: present

- name: Set up Lab2_Rotation
  jenkins_job:
    name: LAB2_Rotation
    config: "{{ job2_rotation }}"
    url: "{{ jenkins_url }}"
    state: present

- name: Set up Lab2_StopContainers
  jenkins_job:
    name: LAB2_StopContainers
    config: "{{ job2_StopContainers }}"
    url: "{{ jenkins_url }}"
    state: present