---
conjur_version: 'EE'

conjur_container_name: 'conjur-master'
conjur_EE_image_name: 'registry2.itci.conjur.net/conjur-appliance:5.0-stable'
conjur_OSS_image_name: 'cyberark/conjur'
conjur_network_name: conjur
conjur_cli_container_name: 'conjur-cli'
conjur_cli_image_name: 'cdemo/conjur-cli:latest'
conjur_account: 'cyberark'
conjur_admin_password: 'Cyberark1'

conjur_EE_port: '443'
conjur_OSS_port: '81'

gogs_internal_port: '3000'
gogs_external_port: '10080'
gogs_container_name: 'gogs'
gogs_image_name: 'gogs/gogs'
gogs_internal_url: "http://{{ gogs_container_name }}:{{ gogs_internal_port }}"
gogs_external_url: "http://{{ ansible_default_ipv4.address }}:{{ gogs_external_port }}"

gogs_account: 'cyber_dev'
gogs_account_email: 'cyber_dev@cyberark.com'
gogs_account_password: 'Cyberark1'
