---
- name: download awx
  git:
    dest: /opt/awx
    clone: yes
    repo: https://github.com/ansible/awx.git

- name: start up awx
  shell: ansible-playbook -i inventory install.yml
  args:
    chdir: /opt/awx/installer

- name: Wait for AWX
  uri:
    url: "{{ awx_url }}"
    return_content: yes
  register: webpage
  until: '"working..." in webpage.content'
  retries: 60
  delay: 3

- name: connect instances to docker network
  shell: |
    docker network connect conjur awx_web
    docker network connect conjur awx_task
  ignore_errors: yes
