---
- name: download awx
  git:
    dest: /opt/awx
    clone: yes
    repo: https://github.com/ansible/awx.git

- name: configure AWX
  shell: |
    cd /opt/awx/installer
    sed -i "s,host_port=80,host_port={{ ansible_port }},g" ./inventory
    sed -i "s,.*default_admin_password=.*,default_admin_password={{ ansible_password }},g" ./inventory
    sed -i "s,# default_admin_user=admin,default_admin_user={{ ansible_user }},g" ./inventory

- name: start up awx
  shell: ansible-playbook -i inventory install.yml
  args:
    chdir: /opt/awx/installer

- name: Wait for AWX
  uri:
    url: "{{ ansible_external_url_login }}"
    validate_certs: no
    return_content: yes
  register: webpage
  until: '"working..." in webpage.content'
  retries: 240
  delay: 2

- name: connect instances to docker network
  shell: |
    docker network connect conjur awx_web
    docker network connect conjur awx_task
  ignore_errors: yes

- pause:
    seconds: 10

- include_tasks: awx.yml

- include_tasks: pas.yml
  when: ansible_pas == 'YES'