---
- name: start gogs
  docker_container:
    name: "{{ gogs_container_name }}"
    image: "{{ gogs_image_name }}"
    state: started
    restart_policy: always
    recreate: yes
    hostname: "{{ gogs_container_name }}"
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ gogs_external_port }}:{{ gogs_internal_port }}"

- name: Wait for gogs to start
  uri:
    url: "{{ gogs_external_url }}/install"
    return_content: yes
  register: webpage
  until: '"Install Steps For First-time Run" in webpage.content'
  retries: 60
  delay: 3

- name: configure gogs user
  shell: |
    docker cp "{{ role_path }}/files/{{ item }}" {{ conjur_cli_container_name }}:/{{ item }}
    docker exec {{ conjur_cli_container_name }} bash -c "cd / && curl -X POST '{{ gogs_internal_url }}/install' -d @{{ item }}"
  with_items:
   - gogs_preseed_installer.properties

- name: Wait for configured gogs to start
  uri:
    url: "{{ gogs_external_url }}"
    return_content: yes
  register: webpage
  until: '"Gogs is a painless self-hosted Git service" in webpage.content'
  retries: 60
  delay: 3

- name: Create jobs for gogs
  shell: |
    docker exec "{{ gogs_container_name }}" bash -c "touch /data/gogs/conf/readme && echo "{Name}" > /data/gogs/conf/readme"
    docker exec {{ conjur_cli_container_name }} curl -u "{{ gogs_account }}:{{ gogs_account_password }}" -X POST -H 'Content-Type: application/json' {{ gogs_internal_url }}/api/v1/user/repos -d '{"name":"{{ item }}", "description":"{{ item }}","private":false,"auto_init":true, "gitignores":"macOS","license":"MIT License"}'
    docker exec {{ conjur_cli_container_name }} bash -c "cd / && git clone {{ gogs_internal_url }}/{{ gogs_account }}/{{ item }}.git"
    docker cp "{{ role_path }}/files/{{ item }}/." {{ conjur_cli_container_name }}:/{{ item }}
    docker exec {{ conjur_cli_container_name }} bash -c "cd /{{ item }} && git add --all && git -c user.name={{ gogs_account }} -c user.email={{ gogs_account_email }} commit -m 'Uploading files.' && git -c user.name={{ gogs_account }} -c user.email={{ gogs_account_email }} push http://{{ gogs_account }}:{{ gogs_account_password }}@{{ gogs_container_name }}:{{ gogs_internal_port }}/{{ gogs_account }}/{{ item }}.git"
  with_items:
    - LAB1_Summon
    - LAB2_Containers
    - LAB2_Rotation
    - LAB2_StopContainers
    - LAB3_AnsibleCCPaim
    - LAB3_AnsibleConjurIdentity
    - LAB3_AnsibleConjurLookup