

- !permit
  role: !group devops
  privileges:
   - read
   - execute
  resource: *variables

- !permit
  role: !group admins
  privileges:
   - read
   - execute
   - update
  resource: *variables

- !permit
  role: !group auditors
  privileges:
   - read
  resource: *variables