---
- !policy
  id: shared_secret_auth
  body:
    - &variables 
      - !variable helloworld_secret
      - !variable database_password
      - !variable web_config_password
      - !variable systema_root_sshkey
      - !variable systemb_root_sshkey
      - !variable aws_access_key
      - !variable aws_secret_key

- !policy
  id: jenkins
  body:
    - !layer hosts
    - !host-factory
      layers: [ !layer hosts ]
    - !permit
      role: !group /admins
      privileges:
        - execute
        - read
      resource: !host-factory

- !policy
  id: tomcat
  body:
    - !layer hosts
    - !host-factory
      layers: [ !layer hosts ]
    - !permit
      role: !layer /jenkins/hosts
      privileges: 
        - execute
        - read
      resource: !host-factory
    - !permit
      role: !group /admins
      privileges:
        - execute
        - read
      resource: !host-factory
      
- !policy
  id: webapp
  body:
    - !layer hosts
    - !host-factory
      layers: [ !layer hosts ]
    - !permit
      role: !layer /jenkins/hosts
      privileges: 
        - execute
        - read
      resource: !host-factory
    - !permit
      role: !group /admins
      privileges:
        - execute
        - read
      resource: !host-factory

- !permit
  role: !layer webapp/hosts
  privileges:
    - read
    - execute
  resource: *variables
  
- !permit
  role: !layer tomcat/hosts
  privileges:
    - read
    - execute
  resource: *variables

- !permit
  role: !layer jenkins/hosts
  privileges:
    - read
    - execute
    - update
  resource: *variables

- !user mike

- !user john

- !user cindy

- !user paul

- !group devops

- !group admins

- !group auditors

- !grant
  role: !group devops
  members:
   - !user john
   - !user paul

- !grant
  role: !group admins
  members:
   - !user mike

- !grant
  role: !group auditors
  members:
   - !user cindy

- !permit
  role: !group devops
  privileges:
   - read
   - execute
  resource: *variables

- !permit
  role: !group admins
  privileges:
   - read
   - execute
   - update
  resource: *variables

- !permit
  role: !group auditors
  privileges:
   - read
  resource: *variables

  - !permit
    role: !group admins
    privileges:
      - read
      - update
      - create
    resources:
      - !policy root