- !policy
  id: frontend
  body:
    - &variables 
      - !variable helloworld_secret
      - !variable database_password
      - !variable web_config_password
      - !variable systema_root_sshkey
      - !variable systemb_root_sshkey
      - !variable aws_access_key
      - !variable aws_secret_key

- !permit
  role: !group /devops
  privileges:
   - read
   - execute
  resource: *variables

- !permit
  role: !group /admins
  privileges:
   - read
   - execute
   - update
  resource: *variables

- !permit
  role: !group /auditors
  privileges:
   - read
  resource: *variables