---
- hosts: aimMachines
  tasks:
    - name: passing options to the lookup
      debug: msg={{ lookup("cyberarkpassword", cyquery)}}
      vars:
        cyquery:
          appid: "AIM_ACCESS"
          query: "safe=CICD_Secrets;folder=root;object=Database-Oracle-OracleDBuser"
          output: "Password,PassProps.UserName,PassProps.Address,PasswordChangeInProcess"


    - name: used in a loop
      debug: msg={{item}}
      with_cyberarkpassword:
          appid: 'AIM_ACCESS'
          query: 'safe=CICD_Secrets;folder=root;object=Database-Oracle-OracleDBuser'
          output: 'Password,PassProps.UserName,PassProps.Address,PasswordChangeInProcess'
