---
- name: Start conjur container
  docker_container:
    name: "{{ conjur_container_name }}"
    image: "{{ conjur_EE_image_name }}"
    state: started
    privileged: yes
    recreate: yes
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ conjur_EE_port }}:443"
    restart_policy: always

- name: configure conjur container
  shell: |
    docker exec {{ conjur_container_name }} evoke configure master -h {{ conjur_container_name }} -p {{ conjur_admin_password }} {{ conjur_account }}

- name: configure cli for EE
  shell: |
    docker exec {{ conjur_cli_container_name }} bash -c "conjur init -u https://{{ conjur_container_name }} -a {{ conjur_account }} <<< yes"
    docker exec {{ conjur_cli_container_name }} conjur authn login -u admin -p {{ conjur_admin_password }}

- include_tasks: conjurFramework.yml