---
- name: Load Conjur tar
  docker_image:
    name: conjur-appliance
    load_path: ../conjur.tar
    state: present
    timeout: 120

- name: Build conjur-cli
  docker_image:
    name: "{{ conjur_cli_image_name }}"
    path: "{{ role_path }}/files/conjur_cli_image/"
    state: present
    force: yes

- name: createConjurNetwork
  docker_network:
    name: "{{ conjur_network_name }}"
    state: present

- name: createConjurVolume
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items:
   - conjur_cert
   - hostfactoryTokens
   - identity

- name: Start conjur container
  docker_container:
    name: "{{ conjur_container_name }}"
    image: "{{ conjur_EE_image_name }}"
    state: started
    privileged: yes
    recreate: yes
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ conjur_EE_port }}:443"
    volumes:
     - "conjur_cert:/opt/conjur/etc/ssl"
    restart_policy: always

- name: Start Conjur CLI
  docker_container:
    name: "{{ conjur_cli_container_name }}"
    image: "{{ conjur_cli_image_name }}"
    state: started
    volumes:
     - "hostfactoryTokens:/hostfactoryTokens"
     - "conjur_cert:/conjur_cert"
     - "identity:/identity"
    restart_policy: always
    networks:
     - name: "{{ conjur_network_name }}"
    recreate: yes
    entrypoint: []
    command: ["sleep", "infinity"]

- name: configure conjur container
  shell: |
    docker exec {{ conjur_container_name }} evoke configure master -h {{ conjur_container_name }} -p {{ conjur_admin_password }} {{ conjur_account }}

- name: configure cli and load policy
  shell: |
    docker exec {{ conjur_cli_container_name }} bash -c "conjur init -u https://{{ conjur_container_name }} -a {{ conjur_account }} <<< yes"
    docker exec {{ conjur_cli_container_name }} conjur authn login -u admin -p {{ conjur_admin_password }}
    docker exec {{ conjur_cli_container_name }} bash -c "conjur policy load --replace root /policy/policy.yaml"

- name: randomizing variables
  shell: |
    docker exec {{ conjur_cli_container_name }} conjur variable values add {{ item }} $(openssl rand -hex 12)
  with_items:
     - shared_secret_auth/helloworld_secret
     - shared_secret_auth/database_password
     - shared_secret_auth/web_config_password
     - shared_secret_auth/systema_root_sshkey
     - shared_secret_auth/systemb_root_sshkey
     - shared_secret_auth/aws_access_key
     - shared_secret_auth/aws_secret_key