---
- name: Build conjur-cli
  docker_image:
    name: "{{ conjur_cli_image_name }}"
    path: "{{ role_path }}/files/conjur_cli_image/"
    state: present
    force: yes

- name: createConjurNetwork
  docker_network:
    name: "{{ conjur_network_name }}"
    state: present

- name: createConjurVolume
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items:
   - hostfactoryTokens
   - identity

- name: Start postgres
  docker_container:
    name: database
    image: postgres:9.3
    state: started
    recreate: yes
    networks:
     - name: "{{ conjur_network_name }}"
    restart_policy: always

- name: Start Conjur
  docker_container:
    name: "{{ conjur_container_name }}"
    image: "{{ conjur_OSS_image_name }}"
    networks:
     - name: "{{ conjur_network_name }}"
    published_ports:
     - "{{ conjur_OSS_port }}:80"
    state: started
    recreate: yes
    env:
       DATABASE_URL: postgres://postgres@database/postgres
       CONJUR_DATA_KEY: Eb/WhB7csC3v68/h4Ye6l/SpSBM5OwqhEfJm9JFFYP0=
    restart_policy: always
    command: server

- name: Start Conjur CLI
  docker_container:
    name: "{{ conjur_cli_container_name }}"
    image: "{{ conjur_cli_image_name }}"
    state: started
    volumes:
     - "hostfactoryTokens:/hostfactoryTokens"
     - "identity:/identity"
    restart_policy: always
    networks:
     - name: "{{ conjur_network_name }}"
    recreate: yes
    entrypoint: []
    command: ["sleep", "infinity"]