---
- name: Check for conjur.tar
  stat:
     path: ../conjur.tar
  register: conjurTar

- include_tasks: conjurEE.yml
  when: conjurTar.stat.exists == True

- include_tasks: conjurOSS.yml
  when: conjurTar.stat.exists == False
