---
- name: start gitlab
  docker_container:
    name: "{{ gitlab_container_name }}"
    image: gitlab/gitlab-ce:latest
    state: started
    restart_policy: always
    recreate: yes
    hostname: gitlab
    networks:
     - name: conjur
    published_ports:
     - "7070:80"
    env:
      GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
      GITLAB_ROOT_EMAIL: "{{ gitlab_root_email }}"
      GITLAB_EXT_URL: "http://gitlab:7070"
      GITLAB_OMNIBUS_CONFIG: | 
        external_url 'http://gitlab:7070'
