---
- name: start gitlab
  docker_container:
    name: "{{ gitlab_container_name }}"
    image: gitlab/gitlab-ce:latest
    state: started
    restart_policy: always
    recreate: yes
    hostname: "{{ gitlab_container_name }}"
    networks:
     - name: "{{ conjur_docker_network }}"
    published_ports:
     - "{{ gitlab_port }}:80"
    env:
      GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
      GITLAB_ROOT_EMAIL: "{{ gitlab_root_email }}"
      GITLAB_EXT_URL: "http://{{ gitlab_container_name }}:{{ gitlab_port }}"
      GITLAB_OMNIBUS_CONFIG: | 
        external_url 'http://gitlab:7070'

- name: wait for port 7070
  wait_for:
    port: 7070
    delay: 60

- name: Create gitlab Project LAB2_Containers
  shell: |
    docker cp "{{ role_path }}/templates/JOB2_Containers" conjur-cli:/
    docker exec conjur-cli bash -c "cd /JOB2_Containers && git init && git add --all && git -c user.name='Cyber Admin' -c user.email='admin@cyberark.com' commit -m 'Initial Commit' && git -c user.name='Cyber Admin' -c user.email='admin@cyberark.com' push --set-upstream http://{{ gitlab_account }}:{{ gitlab_root_password }}@{{ gitlab_url }}/root/LAB2_Containers.git master"
