---
- name: start gitlab
  docker_container:
    name: "{{ gitlab_container_name }}"
    image: gitlab/gitlab-ce:latest
    state: started
    restart_policy: always
    recreate: yes
    hostname: "{{ gitlab_container_name }}"
    networks:
     - name: "{{ conjur_docker_network }}"
    published_ports:
     - "{{ gitlab_port }}:80"
    env:
      GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
      GITLAB_ROOT_EMAIL: "{{ gitlab_root_email }}"

- name: Wait for gitlab to come up
  uri:
    url: "{{ gitlab_url }}"
    return_content: yes
  register: webpage
  until: '"GitLab Community Edition" in webpage.content' 
  retries: 60
  delay: 3

- name: copy files into conjur-cli
  shell: |
    docker cp "{{ role_path }}/templates/JOB2_Containers" conjur-cli:/

- name: create gitlab job2
  shell: |
    docker exec conjur-cli bash -c "cd /JOB2_Containers && git init && git add --all && git -c user.name='Cyber Admin' -c user.email='admin@cyberark.com' commit -m 'Initial Commit' && git -c user.name='Cyber Admin' -c user.email='admin@cyberark.com' push --set-upstream http://{{ gitlab_account }}:{{ gitlab_root_password }}@{{ gitlab_container_name }}/root/LAB2_Containers.git master"
