---
- name: installDependencies
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - curl
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - git
    - make

- name: install jq
  shell: "cd /usr/bin; wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64; chmod +x ./jq"

- name: install PIP
  easy_install:
    name: pip
    state: latest
